title: Home Assistant - Server
views:

  - title: Main
    icon: mdi:home-assistant
    
    cards:

      - type: vertical-stack
        cards:
        
        - type: markdown
          content: >
             **Текущее состояние**
             
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.time
              name: Current Time
              icon: mdi:clock-outline
            - entity: sensor.date
              name: Date
              icon: mdi:calendar-check-outline
              
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.maria_db_size
              name: DB Size
              icon: mdi:database

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Графики** 

        - type: horizontal-stack
          cards:

           - type: gauge
             name: CPU Load
             unit: '%'
             entity: sensor.processor_use
             severity:
                green: 0
                yellow: 60
                red: 85
             
           - type: gauge
             name: Memory Load
             unit: '%'
             entity: sensor.memory_use_percent
             severity:
                green: 0
                yellow: 60
                red: 85
                
        - type: horizontal-stack
          cards:

           - type: gauge
             name: Disk Usage
             unit: '%'
             entity: sensor.disk_use_percent
             severity:
                green: 0
                yellow: 60
                red: 85    
                
           - type: gauge
             name: Free Space
             unit: 'GB'
             entity: sensor.disk_free
             severity:
                red: 2
                yellow: 6
                green: 8
                
        - type: history-graph
          entities:
           - entity: sensor.maria_db_size
             name: Maria DB
                
              
  - title: Weather
    icon: mdi:weather-partly-snowy-rainy
    
    cards:

        - type: weather-forecast
          entity: weather.home
          
          
  - title: СС 2531
    icon: mdi:usb-flash-drive
    
    cards:
    
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Добавление устройств**     

        - type: entities
          title: Добавление Zigbee устройств
          show_header_toggle: false
          entities:
             - entity: input_boolean.zigbee_permit_join
             - entity: timer.zigbee_permit_join
             - entity: sensor.bridge_state
             
  - title: Alarm    
    cards:

        - type: vertical-stack
          cards: 
            - type: entities
              title: Alarm status
              entities:
                 - entity: input_boolean.alarm_status
                 - entity: input_boolean.upper_floor_alarm_status

        - type: vertical-stack
          cards:
          
          - type: entities
            title: Alarm Indicators
            entities:
               #- entity: sensor.0x00158d000345684e_click
                # name:   Entrance Switch
               #- entity: sensor.0x00158d000345684e_linkquality
                # name:   Link
               #- entity: sensor.0x00158d000345684e_battery
                # name:   Battery
               - entity: binary_sensor.0x00158d0004448cf4_contact
                 name: Service Door
                 #- entity: sensor.0x00158d0004448cf4_linkquality
                 #  name:   Link
                 #- entity: sensor.0x00158d0004448cf4_battery
                 #  name:   Battery
               - entity: binary_sensor.0x00158d00041cbac0_contact
                 name: Front Door
                 #- entity: sensor.0x00158d00041cbac0_linkquality
                 #  name:   Link
                 #- entity: sensor.0x00158d00041cbac0_battery
                 #  name:   Battery
               - entity: binary_sensor.0x00158d000449763b_occupancy
                 name: Upper Floor Movement
                  #  name:   Battery
               - entity: binary_sensor.hue_motion_sensor_1_motion
                 name: Living Room Movement
                 #- entity: sensor.0x00158d000449763b_linkquality
                 #  name:   Link
                 #- entity: sensor.0x00158d000449763b_battery
                 #  name:   Battery
                 #- entity: sensor.0x00158d000449763b_illuminance
                 #  name:   Light Status
             